"""Add table User

Revision ID: 41f5deaf586a
Revises: 7db0d150c35a
Create Date: 2026-05-10 12:41:20.794008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41f5deaf586a'
down_revision: Union[str, Sequence[str], None] = '7db0d150c35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('player_turns', sa.Column('player_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'player_turns', 'users', ['player_id'], ['id'])
    op.add_column('playrooms', sa.Column('leader_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'playrooms', 'users', ['leader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playrooms', type_='foreignkey')
    op.drop_column('playrooms', 'leader_id')
    op.drop_constraint(None, 'player_turns', type_='foreignkey')
    op.drop_column('player_turns', 'player_id')
    op.drop_table('users')
    # ### end Alembic commands ###
