"""player turn fix

Revision ID: 47e24c5ed27e
Revises: edeaa8c40ff1
Create Date: 2026-05-10 14:15:24.094859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47e24c5ed27e'
down_revision: Union[str, Sequence[str], None] = 'edeaa8c40ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_turns', 'number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_turns', 'state_updates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_turns', 'state_updates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('player_turns', 'number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
