"""add_answer_variants_to_location

Revision ID: 5ade86bdbb06
Revises: d42f52770e71
Create Date: 2026-05-09 12:00:17.739125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ade86bdbb06'
down_revision: Union[str, Sequence[str], None] = 'd42f52770e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('answer_variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('playrooms', 'active_turn_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('playrooms', 'active_turn_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_column('locations', 'answer_variants')
    # ### end Alembic commands ###
