"""Update master turn

Revision ID: af69ac516136
Revises: 47e24c5ed27e
Create Date: 2026-05-10 19:37:46.074056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af69ac516136'
down_revision: Union[str, Sequence[str], None] = '47e24c5ed27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_turns', sa.Column('answer_variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_turns', 'answer_variants')
    # ### end Alembic commands ###
