"""world add world_rules

Revision ID: bb5d35a8f3c3
Revises: de116cb44842
Create Date: 2026-05-03 15:15:32.344497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5d35a8f3c3'
down_revision: Union[str, Sequence[str], None] = 'de116cb44842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worlds', sa.Column('world_rules', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worlds', 'world_rules')
    # ### end Alembic commands ###
