"""fix relations

Revision ID: d42f52770e71
Revises: fb4a0fe2beb2
Create Date: 2026-05-09 10:13:28.299259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42f52770e71'
down_revision: Union[str, Sequence[str], None] = 'fb4a0fe2beb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playrooms', sa.Column('active_location_id', sa.UUID(), nullable=True))
    op.add_column('playrooms', sa.Column('active_turn_number', sa.Integer(), nullable=False, server_default=sa.text("1")))
    op.create_foreign_key(None, 'playrooms', 'locations', ['active_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playrooms', type_='foreignkey')
    op.drop_column('playrooms', 'active_turn_number')
    op.drop_column('playrooms', 'active_location_id')
    # ### end Alembic commands ###
