"""Add world table

Revision ID: de116cb44842
Revises: 31bcf2acde2e
Create Date: 2026-05-03 13:26:58.967851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'de116cb44842'
down_revision: Union[str, Sequence[str], None] = '31bcf2acde2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worlds',
    sa.Column(
        'id',
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text('gen_random_uuid()')
    ),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('global_goal', sa.String(), nullable=False),
    sa.Column('conflict_core', sa.String(), nullable=False),
    sa.Column('memory_seed', sa.String(), nullable=False),
    sa.Column('power_limits', sa.String(), nullable=False),
    sa.Column('world_constraints', sa.String(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worlds')
    # ### end Alembic commands ###
