"""master turn fix

Revision ID: edeaa8c40ff1
Revises: 41f5deaf586a
Create Date: 2026-05-10 14:11:46.946884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edeaa8c40ff1'
down_revision: Union[str, Sequence[str], None] = '41f5deaf586a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('master_turns', 'result_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('master_turns', 'state_updates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('master_turns', 'state_updates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('master_turns', 'result_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
