STATUS_ACTIVE = 'STATUS_ACTIVE'
STATUS_STARTED = 'STATUS_STARTED'
STATUS_FINISHED = 'STATUS_FINISHED'

# STATUS_ARCHIVED = 'STATUS_ARCHIVED'
# STATUS_PENDING = 'STATUS_PENDING'
# STATUS_EXPIRED = 'STATUS_EXPIRED'

